import type { AnalysisResult } from "@/types";

const PRIORITY_LABELS: Record<string, string> = {
  immediate: "🔴 Immediate",
  "this-week": "🟡 This Week",
  "this-month": "🟢 This Month",
};

const CATEGORY_LABELS: Record<string, string> = {
  revenue: "Revenue",
  operations: "Operations",
  customers: "Customers",
  inventory: "Inventory",
  general: "General",
};

export function exportToMarkdown(result: AnalysisResult, fileName?: string): string {
  const date = new Date(result.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const confidencePct = Math.round(result.confidence * 100);

  let md = `# InsightPilot Analysis Report\n\n`;
  md += `**Generated:** ${date}  \n`;
  if (fileName) md += `**Source:** ${fileName}  \n`;
  md += `**Analysis Confidence:** ${confidencePct}%\n`;

  if (result.dataQualityNote) {
    md += `\n> ⚠️ **Data Quality Note:** ${result.dataQualityNote}\n`;
  }

  md += `\n---\n\n## 💡 Business Insights\n\n`;
  result.insights.forEach((insight) => {
    const cat = CATEGORY_LABELS[insight.category] ?? insight.category;
    md += `### ${insight.id}. ${cat}\n\n`;
    md += `${insight.text}\n\n`;
    md += `*Signal: ${insight.signal}*\n\n`;
  });

  md += `---\n\n## ⚠️ Business Risks\n\n`;
  result.risks.forEach((risk) => {
    const conf = risk.confidence.charAt(0).toUpperCase() + risk.confidence.slice(1);
    const imp = risk.impact.charAt(0).toUpperCase() + risk.impact.slice(1);
    md += `### Risk ${risk.id}\n\n`;
    md += `${risk.text}\n\n`;
    md += `**Confidence:** ${conf} | **Impact:** ${imp}\n\n`;
  });

  md += `---\n\n## ✅ Recommended Action\n\n`;
  md += `**Priority:** ${PRIORITY_LABELS[result.action.priority] ?? result.action.priority}\n\n`;
  md += `${result.action.text}\n\n`;
  md += `*Rationale: ${result.action.rationale}*\n\n`;

  md += `---\n\n*Generated by [InsightPilot](https://github.com/iqbalmbadhan/insightpilot) — AI-powered business insight dashboard.*\n`;

  return md;
}

export function downloadMarkdown(result: AnalysisResult, fileName?: string): void {
  const md = exportToMarkdown(result, fileName);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `insightpilot-report-${Date.now()}.md`;
  a.click();

  URL.revokeObjectURL(url);
}
